# Generated by Django 5.2.1 on 2025-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('soil_nutrient_npk', models.CharField(max_length=100)),
                ('soil_moisture', models.FloatField(help_text='Percentage (%)')),
                ('soil_ph', models.FloatField()),
                ('soil_temperature', models.FloatField(help_text='Temperature in °C')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
