# Generated by Django 5.2.1 on 2025-05-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoilAssessment',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='moisture_level',
            new_name='soil_moisture',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='fertility',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='assessment',
            name='soil_npk',
            field=models.CharField(default='10:10:10', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='soil_ph',
            field=models.DecimalField(decimal_places=2, default='10:10:10', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='soil_temperature',
            field=models.DecimalField(decimal_places=2, default='10:10:10', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(default='10:10:10', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
