# Generated by Django 5.2.1 on 2025-05-16 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_delete_soilassessment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Moisture in %', max_digits=5)),
                ('fertility', models.CharField(help_text='e.g. N:20 P:30 K:40', max_length=100)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=6)),
                ('weather', models.CharField(help_text='e.g. sunny, rainy', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
