# Generated by Django 5.2.1 on 2025-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_soilassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilassessment',
            name='fertility',
            field=models.CharField(max_length=100),
        ),
    ]
